---

-
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: touch 00-login-screen
      shell: touch /etc/dconf/db/local.d/00-login-screen
      when: ansible_os_family == "RedHat"

    - name: add disable-user-list
      lineinfile:
        path: /etc/dconf/db/local.d/00-login-screen
        line: "{{item}}"
        create: yes
      loop:
        - "[org/gnome/login-screen]"
        - "disable-user-list=true"
      when: ansible_os_family == "RedHat"

    - name: add disable Gnome initial setup for users
      dnf:
        name: gnome-initial-setup
        state: absent
      when: ansible_os_family == "RedHat"

    - name: add disable Gnome initial setup for users (debian)
      apt:
        name: gnome-initial-setup
        state: absent
      when: ansible_os_family == "Debiant"

    - name: add gdm profile message (Debian)
      copy:
        src: /home/ansible/templates/gdm.j2
        dest: /etc/motd
        owner: root
        group: root
        force: yes
        mode: u=rw,g=r,o=r
      when: ansible_os_family == "Debian"

    - name: add disable-user-list (Debian)
      copy:
        src: /home/ansible/templates/greeter.dconf-defaults.j2
        dest: /etc/gdm3/greeter.dconf-defaults
        owner: root
        group: root
        force: yes
        mode: u=rw,g=r,o=r
      when: ansible_os_family == "Debian"

    - name: update dconf
      shell: dconf update

    - name: restart gdm
      systemd:
        state: restarted
        name: gdm

...
